src/Entity/Recipe.php
<?php

namespace App\Entity;

use App\Repository\RecipeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RecipeRepository::class)]
class Recipe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $text = null;

    #[ORM\ManyToOne(inversedBy: 'recipes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $owner = null;

    /**
     * @var Collection<int, Category>
     */
    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'recipes')]
    private Collection $categories;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $ingredients = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $teaserImage = null;

    /**
     * @var Collection<int, Comment>
     */
    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'recipe')]
    private Collection $comments;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): static
    {
        $this->text = $text;

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): static
    {
        $this->owner = $owner;

        return $this;
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): static
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
        }

        return $this;
    }

    public function removeCategory(Category $category): static
    {
        $this->categories->removeElement($category);

        return $this;
    }

    public function getIngredients(): ?string
    {
        return $this->ingredients;
    }

    public function setIngredients(string $ingredients): static
    {
        $this->ingredients = $ingredients;

        return $this;
    }

    public function getTeaserImage(): ?string
    {
        return $this->teaserImage;
    }

    public function setTeaserImage(?string $teaserImage): static
    {
        $this->teaserImage = $teaserImage;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setRecipe($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getRecipe() === $this) {
                $comment->setRecipe(null);
            }
        }

        return $this;
    }

    public function getCommentCount(): int
    {
        return $this->comments->count();
    }
}

src/Form/RecipeType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Recipe;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RecipeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('text')
            ->add('ingredients')
            ->add('teaserImage', FileType::class, [
                'label' => 'Titelbild',
                'required' => false,
                'mapped' => false,
            ])
            ->add('categories', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'name',
                'multiple' => true,
                'expanded' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Recipe::class,
        ]);
    }
}

src/Controller/RecipeController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Recipe;
use App\Form\CommentType;
use App\Form\RecipeType;
use App\Repository\RecipeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

#[Route('/')]
final class RecipeController extends AbstractController
{
    #[Route('/', name: 'app_recipe_index', methods: ['GET'])]
    public function index(RecipeRepository $recipeRepository): Response
    {
        return $this->render('recipe/index.html.twig', [
            'recipes' => $recipeRepository->findAll(),
        ]);
    }

    #[Route('/recipe/new', name: 'app_recipe_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
    {
        $recipe = new Recipe();
        $user = $this->getUser();

        $recipe->setOwner($user);

        $form = $this->createForm(RecipeType::class, $recipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $teaserImageFile = $form->get('teaserImage')->getData();
            if ($teaserImageFile) {
                $originalFilename = pathinfo($teaserImageFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$teaserImageFile->guessExtension();

                try {
                    $teaserImageFile->move(
                        $this->getParameter('images_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // Handle Exception
                }

                $recipe->setTeaserImage($newFilename);
            }

            $entityManager->persist($recipe);
            $entityManager->flush();

            return $this->redirectToRoute('app_recipe_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('recipe/new.html.twig', [
            'recipe' => $recipe,
            'form' => $form,
        ]);
    }

    #[Route('/recipe/{id}', name: 'app_recipe_show', methods: ['GET'])]
    public function show(Recipe $recipe, Request $request, EntityManagerInterface $entityManager): Response
    {

        return $this->render('recipe/show.html.twig', [
            'recipe' => $recipe
        ]);
    }

    #[Route('/recipe/{id}/edit', name: 'app_recipe_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Recipe $recipe, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
    {
        $form = $this->createForm(RecipeType::class, $recipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $teaserImageFile = $form->get('teaserImage')->getData();
            if ($teaserImageFile) {
                $originalFilename = pathinfo($teaserImageFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$teaserImageFile->guessExtension();

                try {
                    $teaserImageFile->move(
                        $this->getParameter('images_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // Handle Exception
                }

                $recipe->setTeaserImage($newFilename);
            }
            $entityManager->flush();

            return $this->redirectToRoute('app_recipe_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('recipe/edit.html.twig', [
            'recipe' => $recipe,
            'form' => $form,
        ]);
    }

    #[Route('/recipe/{id}', name: 'app_recipe_delete', methods: ['POST'])]
    public function delete(Request $request, Recipe $recipe, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$recipe->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($recipe);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_recipe_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/recipe/{id}/comment/new', name: 'app_recipe_comment_new', methods: ['GET', 'POST'])]
    public function newComment(Request $request, Recipe $recipe, EntityManagerInterface $entityManager): Response
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $user = $this->getUser();
            $recipe->addComment($comment);
            $user->addComment($comment);
            $comment->setCreatedAt(new \DateTimeImmutable());
            $entityManager->persist($comment);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_recipe_show', ['id' => $recipe->getId()]);
    }

    public function commentForm(Recipe $recipe): Response
    {
        $form = $this->createForm(CommentType::class);

        return $this->render('recipe/_comment_form.html.twig', [
            'form' => $form->createView(),
            'recipe' => $recipe,
        ]);
    }
}

templates/recipe/_comment_form.html.twig
{{ form_start(form, {'action': path('app_recipe_comment_new', {'id': recipe.id}), 'attr': {'id': 'comment-form'} }) }}
{{ form_errors(form) }}
<article class="media">

    <div class="media-content">

        <div class="field">
            {{ form_label(form.text, 'Kommentar eingeben', {'label_attr': {'class': 'label'}}) }}
            <p class="control">
                {{ form_widget(form.text, {'attr': {'class': 'textarea', 'placeholder': 'Ihr Kommentar'}}) }}
            </p>
        </div>
        <div class="field">
            <p class="control">
                {{ form_rest(form) }}
                <button type="submit" class="btn btn-primary">Kommentar senden</button>
            </p>
        </div>
    </div>
</article>
{{ form_end(form) }}

templates/recipe/_delete_form.html.twig
<form method="post" action="{{ path('app_recipe_delete', {'id': recipe.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ recipe.id) }}">
    <button class="btn">Delete</button>
</form>

templates/recipe/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="w-full bg-pinegreen hover:bg-pinegreen-40 text-white font-medium py-2.5 rounded-lg transition-colors">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/recipe/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Recipe{% endblock %}

{% block body %}
    <h1>Edit Recipe</h1>

    {{ include('recipe/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_recipe_index') }}">back to list</a>

    {{ include('recipe/_delete_form.html.twig') }}
{% endblock %}

templates/recipe/index.html.twig
{% extends 'base.html.twig' %}
{% set random_images = [
    'images/placeholder/placeholder1.png',
    'images/placeholder/placeholder2.png',
    'images/placeholder/placeholder3.png'
] %}
{% block title %}Recipe index{% endblock %}

{% block body %}
    <main class="container mx-auto mt-10 max-w-7xl">
        <section>
            <h1 class="font-bold py-5">Willkommen auf Rezeptoria</h1>

            <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-10">
                {% for recipe in recipes %}
                <div class="rounded overflow-hidden shadow-lg flex flex-col">
                    <div class="relative"><a href="{{ path('app_recipe_show', {'id': recipe.id}) }}">
                        {% if recipe.teaserImage %}
                            <img src="{{ asset('uploads/images/' ~ recipe.teaserImage) }}" alt="{{ recipe.title}} Image" class="w-full">
                        {% else %}
                            {% set random_index = random(range(0, random_images|length - 1)) %}
                            {% set random_image = random_images[random_index] %}

                            <img src="{{ asset(random_image) }}" alt="Kein Bild vorhanden" class="w-full">
                        {% endif %}

                        <div class="hover:bg-transparent transition duration-300 absolute bottom-0 top-0 right-0 left-0 bg-gray-900 opacity-25">
                        </div>
                        </a>
                        <div class="absolute top-0 left-0 w-full">
                            {% for category in recipe.categories %}
                                <div class="inline-block text-xs bg-indigo-600 px-4 py-2 text-white mt-3 mr-3 hover:bg-white hover:text-indigo-600 transition duration-500 ease-in-out">
                                    {{ category.name }}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="px-6 py-4 mb-auto">
                        <a href="{{ path('app_recipe_show', {'id': recipe.id}) }}"
                           class="font-medium text-lg inline-block hover:text-indigo-600 transition duration-500 ease-in-out inline-block mb-2">{{ recipe.title }}</a>
                        <p class="text-gray-500 text-sm">
                            {{ recipe.text }}
                        </p>
                    </div>
                    <div class="px-6 py-3 flex flex-row items-center justify-between bg-gray-100">
                        {% if app.user == recipe.owner %}
                            <a href="{{ path('app_recipe_edit', {'id': recipe.id}) }}" class="py-1 text-xs font-regular text-gray-900 mr-1 flex flex-row items-center">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6" height="13px" width="13px">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.832 19.82a4.5 4.5 0 0 1-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 0 1 1.13-1.897L16.863 4.487Zm0 0L19.5 7.125" />
                                </svg>
                                <span class="ml-1">edit</span>
                            </a>
                        {% endif %}
                        <span href="#"
                              class="py-1 text-xs font-regular text-gray-900 mr-1 flex flex-row items-center">
                            <svg class="h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                      d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z">
                                </path>
                            </svg>
                            <span class="ml-1">Kommentare:</strong> {{ recipe.commentCount }}</span>
                        </span>
                    </div>
                </div>

                {% else %}
                    no records found
                {% endfor %}
            </div>
        </section>
    </main>
{% endblock %}

templates/recipe/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Erstelle ein neues Rezept{% endblock %}

{% block body %}
<div class="flex items-center justify-center p-4">
    <div class="max-w-3xl w-full bg-white rounded-xl shadow-lg p-8">
        <h1 class="text-2xl font-bold text-gray-900 mb-6 text-center">Erstelle ein neues Rezept!</h1>

        {{ include('recipe/_form.html.twig') }}

        <div class="mt-6 text-center text-sm text-gray-600">
            <a href="{{ path('app_recipe_index') }}" class="text-pinegreen hover:text-pinegreen-40 font-medium">Zurück</a>
        </div>
    </div>
</div>
{% endblock %}

templates/recipe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recipe{% endblock %}

{% block body %}
<div class="flex items-center justify-center p-4">
    <div class="max-w-5xl w-full bg-white rounded-xl shadow-lg p-8">
        <h1 class="text-2xl font-bold text-gray-900 mb-6 text-center">{{ recipe.title }}</h1>
        {% if recipe.teaserImage %}
            <img src="{{ asset('uploads/images/' ~ recipe.teaserImage) }}" alt="{{ recipe.title}} Image" class="w-full">
        {% endif %}
        <h2>Einleitung</h2>
        <p>{{ recipe.text }}</p>
        <h3>Zutaten</h3>
        <p>{{ recipe.ingredients }}</p>

        <h2>Kommentare</h2>

        {% for comment in recipe.comments %}
            <div>
                <p>{{ comment.text }}</p>
                <small>Geschrieben von {{ comment.createdUser.username }} am {{ comment.createdAt|date('d.m.Y H:i') }}</small>
            </div>
        {% endfor %}

        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            <h3>Neuer Kommentar</h3>
            {{ render(controller('App\\Controller\\RecipeController::commentForm', {'recipe': recipe.id})) }}
        {% else %}
            <p>Sie müssen <a href="{{ path('app_login') }}">angemeldet</a> sein, um einen Kommentar zu schreiben.</p>
        {% endif %}

    <a href="{{ path('app_recipe_index') }}">back to list</a>
        {% if app.user == recipe.owner %}
    <a href="{{ path('app_recipe_edit', {'id': recipe.id}) }}">edit</a>

    {{ include('recipe/_delete_form.html.twig') }}
        {% endif %}
    </div>
</div>
{% endblock %}